############################
## WireGuard installation ##
############################
#
#

--- 
## Install WireGuard prerequests for CentOS/RHEL 7

    - name: Upgrade system packages on CentOS/RHEL
      yum: 
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_os_family == 'RedHat'


    - name : Add Extra Packages for Enterprise Linux (EPEL) repository
      yum:
        name: epel-release
        state: latest
      when: ansible_os_family == 'RedHat'


    - name : Install kernel headers on CentOS/RHEL
      yum:
        name: kernel-devel
        state: latest
      when: ansible_os_family == 'RedHat'

## Install WireGuard prerequests for Debian/Ubuntu

    - name: Install Python 2 if not exist
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      when: ansible_os_family == 'Debian'
 

    - name: Upgrade system packages on Debian/Ubuntu
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == 'Debian'

## Add WireGuard repository and install it

    - name: Add WireGuard repository to CentOS/RHEL 7
      get_url:
        url: "{{ wireguard_repo }}"
        dest: /etc/yum.repos.d/wireguard.repo
      when: ansible_os_family == 'RedHat'


    - name : Add WireGuard repository to Debian
      apt_repository:
        repo: deb http://deb.debian.org/debian/ unstable main
        state: present
        filename: unstable-wireguard.list
        update_cache: yes
      when: ansible_distribution == 'Debian'


    - name: Configure APT to use unstable Debian repository with low priority
      copy:
        src: limit-unstable
        dest: /etc/apt/preferences.d/limit-unstable
      when: ansible_distribution == 'Debian'


    - name : Add WireGuard repository to Ubuntu
      apt_repository:
        repo: ppa:wireguard/wireguard
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'


    - name: Install WireGuard
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - wireguard-dkms 
        - wireguard-tools

## Configure system environment

    - name: Enable packet forwording for IPv4
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes




## Configure WireGuard
    
    - name: Create WireGuard configurations directory
      file:
        dest: /etc/wireguard
        state: directory


    - name: Generate WireGuard private and public keys
      shell: umask 077 && wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey


    - name: Register WireGuard private key as a variable
      slurp:
        src: /etc/wireguard/privatekey
      register: wg_privatekey


    - name: Generate WireGuard configuration file
      template:
        src: wireguard.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: 0600
        force: no

## Set up the firewall if we're gonna
    - name: Set up the firewall
      import_tasks: firewall-setup.yml
      when: manage_firewall

      
## Reboot server to load latest kernel

    - name: Reboot server
      shell: sleep 2 && /sbin/reboot
      async: 1
      poll: 0
      ignore_errors: true


    - name: Waiting for hosts to come back
      wait_for_connection:

## Install current kernel headers on Debian/Ubuntu

    - name: Install kernel headers on Debian/Ubuntu
      shell: apt install -y linux-headers-`uname -r`
      when: ansible_os_family == 'Debian'

## Enable the firewall if it isn't already
    - name: Enable the firewall
      import_tasks: firewall-enable.yml
      when: manage_firewall

## Enable WireGuard kernel module and start service

    - name: Enable WireGuard kernel module
      modprobe:
        name: wireguard
        state: present
      register: wireguard_module_enabled
      until:  wireguard_module_enabled is succeeded
      retries: 10
      delay: 10
      failed_when: wireguard_module_enabled is failure


    - name: Start and enable WireGuard service
      service:
        name: wg-quick@wg0
        state: started
        enabled: yes

